version: '3.4'

services:
  adultswimapi:
    image: adultswimapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3033:3033
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
